services:
  db:
    image: postgres:15
    container_name: cart_final_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cartdb
    ports:
      - "5435:5432"
    volumes:
      - cart_final_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --host=localhost --port=5432 --dbname=cartdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: cart_final_app
    ports:
      - "3006:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/cartdb?schema=public

volumes:
  cart_final_data:
