services:
  app:
    container_name: user_service_app
    build: .
    ports:
      - "3001:3000"
    environment:
      
      DATABASE_URL: "postgresql://docker:docker@db:5432/user_db?schema=public"
    depends_on:
      - db
    

  db:
    container_name: user_service_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: user_db
    volumes:
    
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
